language: perl
os:
  - linux
  # - osx

perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  - sudo apt-get update -q
  - sudo apt-get install -y libdevel-cover-perl
  - cpanm -v --installdeps --notest .
  - cpanm -n Devel::Cover::Report::Coveralls Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Carp

script:
  perl Makefile.PL && make && cover -test -report coveralls
